#!/bin/bash
# =============================================================================
# Generate .env file from environment variables
# =============================================================================
# This script is used by GitHub Actions to generate the .env file on the server
# from GitHub Secrets and Variables.
#
# Usage: ./generate-env.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATEWAY_DIR="$(dirname "$SCRIPT_DIR")"

cat > "$GATEWAY_DIR/.env" << EOF
# Generated by generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit manually - changes will be overwritten on next deploy

# Network Configuration
GRAPHQL_HOST=${GRAPHQL_HOST:-arweave.net}
GRAPHQL_PORT=${GRAPHQL_PORT:-443}
START_HEIGHT=${START_HEIGHT:-0}

# Gateway Identity
AR_IO_WALLET=${AR_IO_WALLET:-}
OBSERVER_WALLET=${OBSERVER_WALLET:-}
ARNS_ROOT_HOST=${ARNS_ROOT_HOST:-}

# Observer Configuration
RUN_OBSERVER=${RUN_OBSERVER:-true}

# Optional Settings
TRUSTED_NODE_URL=${TRUSTED_NODE_URL:-https://arweave.net}
ADMIN_API_KEY=${ADMIN_API_KEY:-}
LOG_LEVEL=${LOG_LEVEL:-info}
EOF

echo "Generated .env file at $GATEWAY_DIR/.env"

